<?php
//Bei den Indices werden Ä, Ö, Ü, ä, ö, ü und ß durch Umschrift (ae, oe, ue, ss) ersetzt, Leerzeichen entfernt und Groß- in Kleinbuchstaben konvertiert.

$bases = array(
	'vd16' => 'http://gateway-bayern.de/VD16+{ID}', 
	'vd17' => 'http://gso.gbv.de/DB=1.28/CMD?ACT=SRCHA&IKT=8002&TRM={ID}', 
	'vd18' => 'http://vd18.de/id/{ID}', 
	'edit16' => 'http://edit16.iccu.sbn.it/scripts/iccu_ext.dll?fn=10&i={ID}',
	'edit' => 'http://edit16.iccu.sbn.it/scripts/iccu_ext.dll?fn=10&i={ID}',
	'swissbib' => 'https://www.swissbib.ch/Record/{ID}',
	'gw' => 'http://gesamtkatalogderwiegendrucke.de/docs/GW{ID}.htm',
	'rero' => 'http://data.rero.ch/01-{ID}/html?view=RERO_V1&lang=de',
	'stcn' => 'http://picarta.pica.nl/DB=3.11/XMLPRS=Y/PPN?PPN={ID}',
	'gbv' => 'http://gso.gbv.de/DB=2.1/PPNSET?PPN={ID}',
	'ppn' => 'http://gso.gbv.de/DB=2.1/PPNSET?PPN={ID}',
	'swb' => 'http://swb.bsz-bw.de/DB=2.1/PPNSET?PPN={ID}',
	'parisbnf' => 'http://catalogue.bnf.fr/ark:/12148/cb{ID}/PUBLIC',
	'loc' => 'https://lccn.loc.gov/{ID}',
	'oenb' => 'http://data.onb.ac.at/rec/{ID}',
	'inka' => 'http://www.inka.uni-tuebingen.de/?inka={ID}',
	'bvb' => 'http://gateway-bayern.de/{ID}',
	'hbz' => 'http://lobid.org/resource/{ID}',
	'hebis' => 'http://orsprod.rz.uni-frankfurt.de/DB=2.1/PPNSET?PPN={ID}',
	'londonbl' => 'http://explore.bl.uk/primo_library/libweb/action/display.do?doc={ID}',
	'denhaagkb' => 'http://opc4.kb.nl/DB=1/PPNSET?PPN={ID}',
	'kopenhagenkb' => 'http://rex.kb.dk/KGL:KGL:{ID}',
	'copac' => 'http://copac.jisc.ac.uk/id/{ID}?style=html',
	'sudoc' => 'http://www.sudoc.fr/{ID}',
	'unicat' => 'http://www.unicat.be/uniCat?func=search&query=sysid:{ID}',
	'sbn' => 'http://id.sbn.it/bid/{ID}',
	'sbb' => 'http://stabikat.de/DB=1/PPNSET?PPN={ID}',
	'lbvoe' => 'http://lb1.dabis.org/PSI/redirect.psi&sessid=---&strsearch=IDU={ID}',
	'uantwerpen' => 'http://anet.be/record/opacuantwerpen/{ID}',
	'josiah' => 'http://josiah.brown.edu/record={ID}',
	'solo' => 'http://solo.bodleian.ox.ac.uk/OXVU1:oxfaleph{ID}',
	'uul' => 'http://aleph.library.uu.nl/F?func=direct&doc_number={ID}',
	'nebis' => 'http://opac.nebis.ch/F?func=direct&local_base=NEBIS&doc_number={ID}',
	'buva' => 'http://permalink.opc.uva.nl/item/{ID}',
	'manumed' => 'http://www.manuscripta-mediaevalia.de/dokumente/html/{ID}'
	);
	
$patternSystems = array(
	'vd16' => '~VD[ ]?16 ([A-Z][A-Z]? [0-9]{1,5})~', 
	'vd17' => '~VD[ ]?17 ([0-9]{1,3}:[0-9]{1,7}[A-Z])~', 
	'vd18' => '~VD ?18 ([0-9]{7,9})~',
	'edit16' => '~EDIT ?[16]{0,2} [A-Z]{4} ?([0-9]{1,10})~',
	'edit' => '~EDIT ?[A-Z]{4} ?([0-9]{1,10})~',
	'swissbib' => '~SWISSBIB ?([0-9]{6,10})~',
	'gw' => '~GW[ ]?([^ ]+)~',
	'rero' => '~RERO ([A-Z][0-9]{8-10})~',
	'stcn' => '~STCN[ ]?([0-9]{8}[0-9X])~',
	'gbv' => '~GBV ([0-9]{9})|GBV ([0-9]{9})~',
	'ppn' => '~PPN ([0-9]{9})|GBV ([0-9]{9})~',
	'swb' => '~SWB ([0-9]{9})~',
	'parisbnf' => '~FRBNF ?([a-z]{1,2}[0-9]{7,10})~',
	'loc' => '~LoC ([0-9]{6,10})~',
	'oenb' => '~ÖNB ?([A-Za-z]{2,3}[0-9]{5,10})~',
	'inka' => '~INKA ?([0-9]{8})~',
	'bvb' => '~BVB (BV[0-9]{9})~',
	'hbz' => '~HBZ ([HT]T[0-9]{9})~',
	'hebis' => '~HeBIS ([0-9]{7,10})~',
	'londonbl' => '~BL (BLL[0-9]{11})~',
	'denhaagkb' => '~Haag KB ([0-9]{9})~',
	'kopenhagenkb' => '~Kopenhagen KB ([A-Z]{2,5}[0-9]{7,12})~',
	'copac' => '~COPAC ([0-9]{1,8})~',
	'sudoc' => '~SUDOC ([0-9]{8,10})~',
	'unicat' => '~UNICAT ([0-9]{7,9})~',
	'sbn' => '~SBN ([A-Z0-9]{8,12})~',
	'sbb' => '~SBB ([0-9]{9})|GBV ([0-9]{9})~',
	'lbvoe' => '~LBVÖ ([A-Z0-9-]+)~',
	'uantwerpen' => '~Antwerpen ([a-z]:[a-z]{3}:[0-9]{7-9})~',
	'josiah' => '~JOSIAH ([a-z][0-9]{6,8})~',
	'solo' => '~SOLO ([0-9]{8,10})~',
	'uul' => '~UUL ([0-9]{8,10})~',
	'nebis' => '~NEBIS ([0-9]{7,9})~',
	'buva' => '~BUvA ([0-9]+)~',
	'manumed' => '~ManuMed obj[0-9]{6,10},?T?~'
	);
	
?>