                <p>
<?php if ($persons): ?>
                    <span class="authorList"><?php echo $persons; ?>:</span>
<?php endif; ?>
<?php if ($item->titleBib and $item->titleCat): ?>
                    <span class="titleBib"><?php echo $item->titleBib; ?>,</span><span class="titleCat"><?php echo $item->titleCat; ?></span> 
<?php elseif ($item->titleBib): ?>
                    <span class="titleBib"><?php echo $item->titleBib; ?>,</span><span class="titleCat">[Recherchierter Titel:] <?php echo $item->titleBib; ?></span>
<?php elseif ($item->titleCat): ?>
                    <span class="titleBib">[Titel im Altkatalog:] <?php echo $item->titleCat; ?>,</span><span class="titleCat"><?php echo $item->titleCat; ?></span> 
<?php endif; ?>
<?php if ($item->volumes > 1): ?>
                    <span class="volumes"><?php echo $item->volumes; ?> Bde., </span>
<?php endif; ?>
<?php if ($published): ?>
                    <span class="published"><?php echo $published; ?></span>
<?php endif; ?>
                    <a id="link<?php echo 'current_'.$count; ?>" href="javascript:toggle('<?php echo 'current_'.$count; ?>')">Mehr</a>
                </p>
                <div id="<?php echo 'current_'.$count; ?>" style="display:none; padding-top:0px; padding-bottom:15px; padding-left:10px;">
<?php if ($sourceLink): ?>
                    <?php echo $sourceLink; ?><br /><?php endif; ?>
<?php if ($item->histShelfmark): ?>                    Altsignatur: <?php echo $item->histShelfmark; ?><br/>
<?php endif; ?>
<?php if ($originalLink): ?>                    <?php echo $originalLink; ?><br />
<?php endif; ?>
<?php if ($item->work['systemWork'] and $item->work['idWork']): ?>                    <?php $refWork = new reference($item->work['systemWork'], $item->work['idWork'], 'work'); ?><?php if ($item->work['titleWork']): ?>Enthaltenes Werk: <a href="<?php echo $refWork->url; ?>" title="Anzeigen in <?php echo $refWork->nameSystem; ?>" target="_blank"><?php echo $item->work['titleWork']; ?></a><?php else: ?>Datensatz Werk anzeigen: <?php echo $refWork->link; ?><?php endif; ?><br />
<?php endif; ?>
<?php if ($digiLink): ?>                    <?php echo $digiLink; ?><br />
<?php endif; ?>
<?php if ($item->manifestation['systemManifestation'] and $item->manifestation['idManifestation']): ?>                    Nachweis: <?php $proof = new reference($item->manifestation['systemManifestation'], $item->manifestation['idManifestation']); echo $proof->link; ?><?php else: ?> <?php echo 'Ausgabe nicht bestimmbar'; ?><br />
<?php endif; ?>
<?php if ($copiesHAB): ?>                    <?php echo $copiesHAB; ?><br />
<?php endif; ?>
<?php if ($item->comment): ?>                    <?php echo makeComment($item->comment); ?>
<?php endif; ?>
                </div>
